name: Main branch
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  perform:
    uses: cloudposse/github-actions-workflows/.github/workflows/complex-workflow-main-branch.yml@main
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
      registry: 252494810635.dkr.ecr.us-east-2.amazonaws.com
    secrets:
      github-private-actions-pat: "${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"