name: Reusable - Release
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
      registry:
        description: "Docker registry"
        required: false
        type: string
        default: registry.hub.docker.com
      version:
        required: true
        type: string
    secrets:
      github-private-actions-pat:
        required: true

permissions:
  contents: write

jobs:
  promote:
    runs-on: ["self-hosted"]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Branch From Specific Tag
        uses: satya-500/create-branch-from-tag@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          branch: release/${{ inputs.version }}
          from: tags/${{ inputs.version }}

      - name: Promote Docker image
        uses: EuphoricSystems/docker-promote-image@1.0.0
        with:
          src: ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.repository }}:sha-${{ github.sha }}
          destinations: ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.repository }}:${{ github.event.release.tag_name }}

    outputs:
      image: ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.repository }}
      tag: ${{ github.event.release.tag_name }}

  deploy_staging:
    runs-on: ["self-hosted"]
    environment:
      name: staging
      url: ${{ steps.deploy.outputs.webapp-url }}
    needs: [ promote ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Private actions
        uses: actions/checkout@v3
        with:
          repository: cloudposse/actions-private
          ref: main
          token: ${{ secrets.github-private-actions-pat }}
          path: .github/actions

      - name: Deploy
        id: deploy
        uses: ./.github/actions/deploy
        with:
          stack: staging
          environment:  staging
          namespace: staging
          image: ${{ needs.promote.outputs.image }}
          image-tag: ${{ needs.promote.outputs.tag }}
          operation: apply

  deploy_production:
    runs-on: ["self-hosted"]
    environment:
      name: production
      url: ${{ steps.deploy.outputs.webapp-url }}
    needs: [ deploy_staging ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Private actions
        uses: actions/checkout@v3
        with:
          repository: cloudposse/actions-private
          ref: main
          token: ${{ secrets.github-private-actions-pat }}
          path: .github/actions

      - name: Deploy
        id: deploy
        uses: ./.github/actions/deploy
        with:
          stack: production
          environment:  production
          namespace: production
          image: ${{ needs.promote.outputs.image }}
          image-tag: ${{ needs.promote.outputs.tag }}
          operation: apply
